name: "test"
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: teaxyz/setup@v0
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          key: ci-pnpm
          path: |
            ./pnpm
            ./.pnpm-store
            ./node_modules
            .svelte-kit
      - name: install app dependencies
        run: tea -ES xc setup
      - name: lint
        run: tea -ES pnpm lint
      - name: build
        run: tea -ES xc build