name: 'test'
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: teaxyz/setup@v0
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          key: ci-pnpm
          path: |
            ./pnpm
            ./.pnpm-store
            ./node_modules
            ./app/node_modules
            ./app/.svelte-kit
            ./functions/node_modules
      - name: install app dependencies
        run: tea -ES xc setup
      - name: lint
        run: tea -E pnpm -r lint
      - name: build
        run: tea -ES xc build
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: teaxyz/setup@v0
      - uses: actions/checkout@v3
      - name: cache node_modules
        uses: actions/cache@v3
        with:
          key: ci-pnpm
          path: |
            ./pnpm
            ./.pnpm-store
            ./node_modules
            ./app/node_modules
            ./app/.svelte-kit
            ./functions/node_modules
      - run: tea -SE xc build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FREEDIVE_SUPERHOME }}'
          projectId: freedive-superhome

